### ISSUE TITLE
unable to find any fan device

### ISSUE THREAD

**Issue by mo523** [ichiriac/ubuntu-smart-fan#1]
Coming from this question:
https://askubuntu.com/questions/1097474/dell-vostro-200-fan-speeds
Got pwmconfig to work, but not your program.
Attatched is my debug info:
[debug.txt](https://github.com/ichiriac/ubuntu-smart-fan/files/2688966/debug.txt)

**Comment by ichiriac** [comment]
Hi @mo523,

Thanks for debug, as I can see hwmon2 (it8718) have 3 fans, the system does not handles yets multiple fans, but it should anyway control the first fan :

- pwm1 => level of fan speed (from 0  disabled to 255 maximum speed)
- pwm1_enable => 2 it's the automatic mode, 1 it's the manual mode (when the program runs)
- temp1_input => temperature related to pwm1

Here the program tries to also read the name of the fan1 (located into the file fan1_label) but as seen in the debug file it's not present on your system, the error may come from this point.

In order to test it, you can try this command that puts a default name on the fan1, I'll fix it soon :

```
sudo echo "no-name" > /sys/class/hwmon/hwmon2/fan1_label
```

I will try to support multiple fans by using your debug file / as on my computer I have only one.

**Comment by ichiriac** [comment]
Hi @mo523,

I've made a new release `1.0.7` in order to handle multiple fans - in order to test it you can run :

```
sudo npm update -g ubuntu-smart-fan 
```

With this version it will work on your system and also control each fan

**Comment by mo523** [comment]
Cool! Thanks so much. I'm not home right now so I can't mess around with my computer, but I ssh'd into it and updated and it reads the fan info. The display isn't working quite right but I'm pretty sure that it is an issue with my ssh client. I'll let you know when I have a chance to check the actual computer
